#!/usr/bin/env python3
"""Author amendment 14 (order B4 C29-C34): environment recovery —
append-only after the byte-pinned amendment 11.

The a9 lesson is enforced structurally: a PUBLISHED (git-tracked)
amendment can never be regenerated by this script; before
publication, regeneration requires the explicit flag and the file
must not be tracked. Amendments 1-11 are never touched."""
import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tools"))
import b4_authority as b4a  # noqa: E402


def sha_file(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pre-publication-regenerate",
                    action="store_true")
    args = ap.parse_args()
    out = b4a.AMENDMENT_14_PATH
    if out.exists():
        tracked = subprocess.run(
            ["git", "-C", str(REPO), "ls-files", "--error-unmatch",
             str(out.relative_to(REPO))],
            capture_output=True).returncode == 0
        if tracked:
            raise SystemExit(
                "REFUSED: amendment 14 is PUBLISHED history — "
                "append a later amendment, never regenerate")
        if not args.pre_publication_regenerate:
            raise SystemExit(
                "REFUSED: amendment 14 exists (unpublished); pass "
                "--pre-publication-regenerate to re-author before "
                "its first commit")
        out.unlink()
    if sha_file(b4a.AMENDMENT_13_PATH) != b4a.AMENDMENT_13_SHA:
        raise SystemExit(
            "REFUSED: amendment 13 bytes differ from the pinned "
            "history — nothing is authored over a broken chain")
    if sha_file(b4a.INCIDENT_RECORD_PATH) != \
            b4a.INCIDENT_RECORD_SHA:
        raise SystemExit(
            "REFUSED: the incident record bytes differ from the "
            "pinned digest")
    pins = {rel: sha_file(REPO / rel) for rel in (
        "tools/b4_authority.py", "tools/b4_run_cell.py",
        "tools/b4_campaign_executor.py",
        "tools/b4_campaign_ledger.py",
        "tools/b4_campaign_orchestrator.py",
        "tools/b4_adjudicator.py",
        "tools/materialize_b4_causal_sac.py",
        "pipeline_plugins/rl_pipeline_with_validation.py",
        "tests/test_b4_materializer_authority.py")}
    a14 = {
        "schema": ("agent_multi.b4_superseding_design_amendment."
                   "v12_full_checkout_external_custody"),
        "amends_amendment_13_sha256": b4a.AMENDMENT_13_SHA,
        "order": ("C39-C42 (checkout authority order 2026-09-07): "
                  "the reviewed commit must BE the executed "
                  "commit — the authority binds the ENTIRE "
                  "checkout (exact HEAD == pinned_commit, clean "
                  "index and tracked worktree, no untracked/"
                  "ignored shadow-capable source), and the "
                  "productive acta moves OUT of the candidate "
                  "repository to the fixed private "
                  "reviewer-authority root."),
        "change_disclosure": (
            "authority custody ONLY: verify_checkout_identity() "
            "(HEAD/clean/shadow rules; RECOVERY_SURFACE_FILES "
            "demoted to a human review index); "
            "_open_private_authority_file() descriptor-first "
            "walk (O_NOFOLLOW every component, 0700/uid on the "
            "authority chain, exact 0600 file, one read stream); "
            "RECOVERY_AUDIT_RECORD_PATH relocated under "
            "~/.config/agent-multi/reviewer_authority/ (repo "
            "JSONs grant nothing; template only); witness v2 "
            "adds the checkout tree; honest custody-not-"
            "authorship prose. No scientific, population, data, "
            "genesis, comparator, resource-limit or scheduling "
            "change."),
        "scientific_change":
            "NONE — full-checkout identity and external custody only",
        "final_code_pins": pins,
        "chronology_truth": (
            "authored AFTER the C39-C42 PRE freeze and after all "
            "corrected code and tests were finalized and hashed "
            "from disk; amendments 1-13 untouched; the real "
            "Musashi acta remains ABSENT (external root not "
            "created by candidate code) and the v6 launch "
            "remains CLOSED"),
    }
    body = {k: a14[k] for k in sorted(a14)}
    a14["amendment_sha256"] = hashlib.sha256(json.dumps(
        body, sort_keys=True).encode()).hexdigest()
    out.write_text(json.dumps(a14, indent=1))
    print(json.dumps({"amendment_14_sha256_field":
                      a14["amendment_sha256"],
                      "file_sha256": sha_file(out)}, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
