#!/usr/bin/env python3
"""Author amendment 13 (order B4 C29-C34): environment recovery —
append-only after the byte-pinned amendment 11.

The a9 lesson is enforced structurally: a PUBLISHED (git-tracked)
amendment can never be regenerated by this script; before
publication, regeneration requires the explicit flag and the file
must not be tracked. Amendments 1-11 are never touched."""
import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tools"))
import b4_authority as b4a  # noqa: E402


def sha_file(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pre-publication-regenerate",
                    action="store_true")
    args = ap.parse_args()
    out = b4a.AMENDMENT_13_PATH
    if out.exists():
        tracked = subprocess.run(
            ["git", "-C", str(REPO), "ls-files", "--error-unmatch",
             str(out.relative_to(REPO))],
            capture_output=True).returncode == 0
        if tracked:
            raise SystemExit(
                "REFUSED: amendment 13 is PUBLISHED history — "
                "append a later amendment, never regenerate")
        if not args.pre_publication_regenerate:
            raise SystemExit(
                "REFUSED: amendment 13 exists (unpublished); pass "
                "--pre-publication-regenerate to re-author before "
                "its first commit")
        out.unlink()
    if sha_file(b4a.AMENDMENT_12_PATH) != b4a.AMENDMENT_12_SHA:
        raise SystemExit(
            "REFUSED: amendment 12 bytes differ from the pinned "
            "history — nothing is authored over a broken chain")
    if sha_file(b4a.INCIDENT_RECORD_PATH) != \
            b4a.INCIDENT_RECORD_SHA:
        raise SystemExit(
            "REFUSED: the incident record bytes differ from the "
            "pinned digest")
    pins = {rel: sha_file(REPO / rel) for rel in (
        "tools/b4_authority.py", "tools/b4_run_cell.py",
        "tools/b4_campaign_executor.py",
        "tools/b4_campaign_ledger.py",
        "tools/b4_campaign_orchestrator.py",
        "tools/b4_adjudicator.py",
        "tools/materialize_b4_causal_sac.py",
        "pipeline_plugins/rl_pipeline_with_validation.py",
        "tests/test_b4_materializer_authority.py")}
    a13 = {
        "schema": ("agent_multi.b4_superseding_design_amendment."
                   "v11_recovery_custody"),
        "amends_amendment_12_sha256": b4a.AMENDMENT_12_SHA,
        "order": ("C35-C38 (recovery authority order 2026-09-07): "
                  "the acta becomes a VERIFIED OBJECT "
                  "(descriptor-bound, owner/mode checked, canonical "
                  "date, 40-hex pinned commit naming an existing "
                  "git commit whose reviewed surface byte-matches "
                  "the live surface, LATEST amendment digest); the "
                  "typed recovery witness is RE-DERIVED by "
                  "claim_attempt, issue_lease, verify_lease, "
                  "execute_cell and run_campaign — no public "
                  "sequence reaches constructors, pipeline or CUDA "
                  "with the gate closed; the witness flows through "
                  "claim, lease, per-attempt binding, terminals, "
                  "seal intent, campaign report and both verifiers."),
        "change_disclosure": (
            "recovery authority custody ONLY: read_recovery_acta() "
            "verified reader + typed witness; witness re-derivation "
            "on every execution path incl. the standalone CLI; "
            "claim schema + recovery_acta_sha256; lease schema v3 "
            "+ recovery_acta_sha256 + pinned_execution_commit; "
            "binding v2, COMPLETED and typed-failure terminals, "
            "seal intent and campaign report carry generation/acta/"
            "pinned-commit/latest-amendment; both verifiers "
            "re-derive all four. No population, config, data, "
            "genesis, comparator, limit or ordering change."),
        "scientific_change":
            "NONE — recovery authority custody only",
        "final_code_pins": pins,
        "chronology_truth": (
            "authored AFTER the C35-C38 PRE freeze and after all "
            "corrected code and tests were finalized and hashed "
            "from disk; amendments 1-12 untouched; the real "
            "Musashi recovery acta remains ABSENT and the v6 "
            "launch remains CLOSED"),
    }
    body = {k: a13[k] for k in sorted(a13)}
    a13["amendment_sha256"] = hashlib.sha256(json.dumps(
        body, sort_keys=True).encode()).hexdigest()
    out.write_text(json.dumps(a13, indent=1))
    print(json.dumps({"amendment_13_sha256_field":
                      a13["amendment_sha256"],
                      "file_sha256": sha_file(out)}, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
