#!/usr/bin/env python3
"""Author amendment 15 (order B4 C29-C34): environment recovery —
append-only after the byte-pinned amendment 11.

The a9 lesson is enforced structurally: a PUBLISHED (git-tracked)
amendment can never be regenerated by this script; before
publication, regeneration requires the explicit flag and the file
must not be tracked. Amendments 1-11 are never touched."""
import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tools"))
import b4_authority as b4a  # noqa: E402


def sha_file(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pre-publication-regenerate",
                    action="store_true")
    args = ap.parse_args()
    out = b4a.AMENDMENT_15_PATH
    if out.exists():
        tracked = subprocess.run(
            ["git", "-C", str(REPO), "ls-files", "--error-unmatch",
             str(out.relative_to(REPO))],
            capture_output=True).returncode == 0
        if tracked:
            raise SystemExit(
                "REFUSED: amendment 15 is PUBLISHED history — "
                "append a later amendment, never regenerate")
        if not args.pre_publication_regenerate:
            raise SystemExit(
                "REFUSED: amendment 15 exists (unpublished); pass "
                "--pre-publication-regenerate to re-author before "
                "its first commit")
        out.unlink()
    if sha_file(b4a.AMENDMENT_14_PATH) != b4a.AMENDMENT_14_SHA:
        raise SystemExit(
            "REFUSED: amendment 14 bytes differ from the pinned "
            "history — nothing is authored over a broken chain")
    if sha_file(b4a.INCIDENT_RECORD_PATH) != \
            b4a.INCIDENT_RECORD_SHA:
        raise SystemExit(
            "REFUSED: the incident record bytes differ from the "
            "pinned digest")
    pins = {rel: sha_file(REPO / rel) for rel in (
        "tools/b4_authority.py", "tools/b4_run_cell.py",
        "tools/b4_campaign_executor.py",
        "tools/b4_campaign_ledger.py",
        "tools/b4_campaign_orchestrator.py",
        "tools/b4_adjudicator.py",
        "tools/materialize_b4_causal_sac.py",
        "pipeline_plugins/rl_pipeline_with_validation.py",
        "tests/test_b4_materializer_authority.py")}
    a15 = {
        "schema": ("agent_multi.b4_superseding_design_amendment."
                   "v13_runtime_recovery"),
        "amends_amendment_14_sha256": b4a.AMENDMENT_14_SHA,
        "v6_incident_order_sha256": b4a.V6_INCIDENT_ORDER_SHA,
        "order": ("C43-C48 (runtime recovery order 2026-09-07): "
                  "the first v6 dispatch died before the first "
                  "gradient on a None progress callback handed "
                  "to SB3, and the deterministic FAILED terminal "
                  "was left unsealed (UNCERTAIN). This amendment "
                  "records the append-only v7 recovery."),
        "change_disclosure": (
            "runtime recovery ONLY: (C43) per-cell MANDATORY "
            "progress telemetry materialized in the effective "
            "config (both keys -> one contained, cell-unique "
            "file) + compose_learn_callbacks() typed composition "
            "(SB3 never receives None; b4_require_progress "
            "refuses before model.learn; F9.2 preserved); (C44) "
            "run_campaign seals an INTEGRAL typed failure "
            "terminal under the same lock after revalidating "
            "claim/lease/terminal/authority — deterministic "
            "failures adjudicate TERMINAL_<TYPE>, never "
            "UNCERTAIN; absent/partial terminals still block; no "
            "default continuation after a failure; (C45) "
            "generation v7 with fresh provenance ledger, the v6 "
            "root immutable, 39.1 s prior charge (36.0 v5 + 3.1 "
            "v6); (C47) acta v3 at a NEW external filename binds "
            "commit, clean tree, generation and the LATEST "
            "amendment; stale v6 template digest corrected to an "
            "unambiguous placeholder. No population, config, "
            "data, genesis, comparator, budget, seed or "
            "scheduling change."),
        "scientific_change":
            "NONE — runtime callback/seal recovery only",
        "campaign_generation_v7": b4a.CAMPAIGN_GENERATION,
        "supersedes_generation": b4a.V6_GENERATION,
        "supersedes_results_root_logical":
            b4a.V6_RESULTS_ROOT_LOGICAL,
        "v7_results_root_logical": b4a.V7_RESULTS_ROOT_LOGICAL,
        "prior_generations_gpu_seconds_charged":
            b4a.PRIOR_GENERATIONS_GPU_SECONDS,
        "final_code_pins": pins,
        "chronology_truth": (
            "authored AFTER the C43-C48 PRE freeze and after all "
            "corrected code and tests were finalized and hashed "
            "from disk; amendments 1-14 untouched; the real "
            "Musashi v7 acta remains ABSENT and the v7 launch "
            "remains CLOSED"),
    }
    body = {k: a15[k] for k in sorted(a15)}
    a15["amendment_sha256"] = hashlib.sha256(json.dumps(
        body, sort_keys=True).encode()).hexdigest()
    out.write_text(json.dumps(a15, indent=1))
    print(json.dumps({"amendment_15_sha256_field":
                      a15["amendment_sha256"],
                      "file_sha256": sha_file(out)}, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
