#!/usr/bin/env python3
"""Author amendment 12 (order B4 C29-C34): environment recovery —
append-only after the byte-pinned amendment 11.

The a9 lesson is enforced structurally: a PUBLISHED (git-tracked)
amendment can never be regenerated by this script; before
publication, regeneration requires the explicit flag and the file
must not be tracked. Amendments 1-11 are never touched."""
import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "tools"))
import b4_authority as b4a  # noqa: E402


def sha_file(p):
    return hashlib.sha256(Path(p).read_bytes()).hexdigest()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--pre-publication-regenerate",
                    action="store_true")
    args = ap.parse_args()
    out = b4a.AMENDMENT_12_PATH
    if out.exists():
        tracked = subprocess.run(
            ["git", "-C", str(REPO), "ls-files", "--error-unmatch",
             str(out.relative_to(REPO))],
            capture_output=True).returncode == 0
        if tracked:
            raise SystemExit(
                "REFUSED: amendment 12 is PUBLISHED history — "
                "append a later amendment, never regenerate")
        if not args.pre_publication_regenerate:
            raise SystemExit(
                "REFUSED: amendment 12 exists (unpublished); pass "
                "--pre-publication-regenerate to re-author before "
                "its first commit")
        out.unlink()
    if sha_file(b4a.AMENDMENT_11_PATH) != b4a.AMENDMENT_11_SHA:
        raise SystemExit(
            "REFUSED: amendment 11 bytes differ from the pinned "
            "history — nothing is authored over a broken chain")
    if sha_file(b4a.INCIDENT_RECORD_PATH) != \
            b4a.INCIDENT_RECORD_SHA:
        raise SystemExit(
            "REFUSED: the incident record bytes differ from the "
            "pinned digest")
    pins = {rel: sha_file(REPO / rel) for rel in (
        "tools/b4_authority.py", "tools/b4_run_cell.py",
        "tools/b4_campaign_executor.py",
        "tools/b4_campaign_ledger.py",
        "tools/b4_campaign_orchestrator.py",
        "tools/b4_adjudicator.py",
        "tools/materialize_b4_causal_sac.py",
        "pipeline_plugins/rl_pipeline_with_validation.py",
        "tests/test_b4_materializer_authority.py")}
    a12 = {
        "schema": ("agent_multi.b4_superseding_design_amendment."
                   "v10_environment_recovery"),
        "amends_amendment_11_sha256": b4a.AMENDMENT_11_SHA,
        "incident_record_sha256": b4a.INCIDENT_RECORD_SHA,
        "order": ("C29-C34 (environment recovery order "
                  "2026-09-06): the first dispatch failed before "
                  "any gradient because the launching interpreter "
                  "lacked the sac_agent entry point; the failure "
                  "escaped the typed-terminal boundary and left "
                  "cell o2022_seed101 AMBIGUOUS_CLAIM. This "
                  "amendment records the append-only v6 recovery."),
        "change_disclosure": (
            "environment recovery ONLY: (C29) the incident frozen "
            "as regression from a real filtered entry-point "
            "registry; (C30) zero-write environment preflight — "
            "interpreter/versions/CUDA/entry points/effective "
            "imports from the frozen checkout/dependencies/live "
            "authority — refusing BEFORE claim, wired into the "
            "dry-run and the execute path; (C31) total post-claim "
            "exception boundary: plugin load, constructors, "
            "pipeline, scoring and verification all produce typed "
            "terminals (FAILED_PLUGIN_ENVIRONMENT/"
            "FAILED_CONSTRUCTION/FAILED_PREFLIGHT_TYPED); (C32) "
            "generation v6 with fresh provenance-bearing ledger, "
            "identical twelve-cell scientific identity, the fixed "
            "0.01h prior charge deducted from the never-restarting "
            "96h ceiling, superseded v5 root and ambiguous attempt "
            "preserved byte-exact and structurally unreadable by "
            "v6. No population, config, data, genesis, comparator, "
            "limit or ordering change."),
        "scientific_change": "NONE — environment recovery only",
        "campaign_generation_v6": b4a.CAMPAIGN_GENERATION,
        "supersedes_generation":
            b4a.AUTHORIZED_CAMPAIGN_GENERATION,
        "supersedes_results_root_logical":
            b4a.V5_RESULTS_ROOT_LOGICAL,
        "v6_results_root_logical": b4a.V6_RESULTS_ROOT_LOGICAL,
        "prior_generations_gpu_seconds_charged":
            b4a.PRIOR_GENERATIONS_GPU_SECONDS,
        "final_code_pins": pins,
        "chronology_truth": (
            "authored AFTER the C29-C34 PRE freeze and after all "
            "corrected code and tests were finalized and hashed "
            "from disk; amendments 1-11 untouched; the v6 launch "
            "remains CLOSED until the external Musashi "
            "recovery-audit acta pins the recovered commit"),
    }
    body = {k: a12[k] for k in sorted(a12)}
    a12["amendment_sha256"] = hashlib.sha256(json.dumps(
        body, sort_keys=True).encode()).hexdigest()
    out.write_text(json.dumps(a12, indent=1))
    print(json.dumps({"amendment_12_sha256_field":
                      a12["amendment_sha256"],
                      "file_sha256": sha_file(out)}, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
